ALTER TABLE player_profiles ADD COLUMN health INTEGER NOT NULL DEFAULT 100;
ALTER TABLE player_profiles ADD COLUMN max_health INTEGER NOT NULL DEFAULT 100;
ALTER TABLE player_profiles ADD COLUMN mana INTEGER NOT NULL DEFAULT 50;
ALTER TABLE player_profiles ADD COLUMN max_mana INTEGER NOT NULL DEFAULT 50;
ALTER TABLE player_profiles ADD COLUMN movement INTEGER NOT NULL DEFAULT 100;
ALTER TABLE player_profiles ADD COLUMN max_movement INTEGER NOT NULL DEFAULT 100;
